---
title: "p8105_hw6_iho2104"
author: "Ixtaccihuatl Obregon"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(boot)
library(broom)
library(purrr)
library(ggplot2)
library(modelr)
```

# Problem 1 

```{r}

```

# Problem 2

Load weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Bootstrap and r_sq and log_product

```{r}
set.seed(2023)

boot_straps = weather_df |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin + prcp, data = .)),
    results_1 = map(models, glance),
    results_2 = map(models, tidy)) |> 
  select(-strap, -models) |> 
  unnest() |>
  select(.id, r.squared, term, estimate) |> 
  filter(term !="(Intercept)") |> 
  pivot_wider(names_from = term, values_from = estimate) |> 
 mutate(
    tmin = as.numeric(tmin),
    prcp = as.numeric(prcp),
    log_product = log(tmin * prcp)
  )

```

Distribution

```{r}

ggplot(boot_straps, aes(x = r.squared)) +
  geom_histogram(bins = 100, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Distribution of R-squared Estimates",
       x = "R-squared",
       y = "Frequency")


ggplot(boot_straps, aes(x = log_product)) +
  geom_histogram(bins = 100, fill = "green", color = "black", alpha = 0.7) +
  labs(title = "Distribution of log_product Estimates",
       x = "log_product",
       y = "Frequency")
```

CI Intervals

```{r}

boot_straps |>
  select(r.squared, log_product) |> 
  pivot_longer(
    r.squared:log_product, 
    names_to = "variable", 
    values_to = "estimate"
  ) |> 
  group_by(variable) |> 
  summarize(
    lower_ci = quantile(estimate, 0.025, na.rm = TRUE), 
    upper_ci = quantile(estimate, 0.975, na.rm = TRUE), 
) |> 
  knitr::kable()

```

# Problem 3 

Load and clean the data

```{r}
birthweight_df = read.csv("birthweight.csv") 
str(birthweight_df)
summary(birthweight_df)

birthweight_df_tidy = birthweight_df |> 
  janitor::clean_names() |> 
  mutate( 
    gaweeks = as.factor(gaweeks),
    ppbmi = as.factor(ppbmi), 
    smoken = as.factor(smoken)
    )
str(birthweight_df_tidy)

missing_values = colSums(is.na(birthweight_df_tidy))
print(missing_values)

```

Regression model for birth weight 

```{r}
bwt_model_1 = lm(bwt ~ gaweeks + smoken, data = birthweight_df_tidy)
bwt_model_2 = lm(bwt ~ blength + gaweeks , data = birthweight_df_tidy)
bwt_model_3 = lm(bwt ~ bhead*blength*babysex , data = birthweight_df_tidy)

summary(bwt_model_1)
summary(bwt_model_2)
summary(bwt_model_3)

birthweight_df_tidy |> 
  add_predictions(bwt_model_1) |> 
  add_residuals(bwt_model_1) |> 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(color = "blue") +
  geom_smooth(method = "loess", color = "red") +
  labs(title = "Residuals vs. Fitted Values",
       x = "Fitted Values",
       y = "Residuals")

birthweight_df_tidy |> 
  add_predictions(bwt_model_2) |> 
  add_residuals(bwt_model_2) |> 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(color = "blue") +
  geom_smooth(method = "loess", color = "red") +
  labs(title = "Residuals vs. Fitted Values",
       x = "Fitted Values",
       y = "Residuals")

birthweight_df_tidy |> 
  add_predictions(bwt_model_3) |> 
  add_residuals(bwt_model_3) |> 
ggplot(aes(x = pred, y = resid)) +
  geom_point(color = "blue") +
  geom_smooth(method = "loess", color = "red") +
  labs(title = "Residuals vs. Fitted Values",
       x = "Fitted Values",
       y = "Residuals")
```

Comparing 

```{r}
cv_df = 
  crossv_mc(birthweight_df_tidy,1000) 

cv_df =
  cv_df |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df =
  cv_df |>
  mutate(
    bwt_model_1a  = map(train, \(df) bwt_model_1),
    bwt_model_2a  = map(train, \(df) bwt_model_2),
    bwt_model_3a  = map(train, \(df) bwt_model_3)) |> 
  mutate(
    rmse_1 = map2_dbl(bwt_model_1a, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_2 = map2_dbl(bwt_model_2a, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_3 = map2_dbl(bwt_model_3a, test, \(mod, df) rmse(model = mod, data = df)))

cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```
